function glossary = glossaryNS(mode)

    % Enumerate the reference strings used in the library
    if mode == "BC"
        glossary = ...
            ["u"      , "Linear in u"; ...
            "n"      , "Inhomogeneous normal"; ...
            "unu"      , "Normal projection of squared velocity"; ...
            "unn"      , "Normal with u"; ...
            "u3"        , "Linear in u with velocity square pre-factor"; ...
            "dnu"       , "Normal derivative of velocity"; ...
            "du_n"      , "Gradient of normal velocity"; ...
            "uu_x"      , "Advection term"; ...
            "u2n"       , "Linear in n with velocity square prefactor"; ...
            "du2"       , "Gradient of velocity squared"; ...
            "u_xx"      , "Laplacian of u"; ...
            ];
        % (two terms ignored because of linear independence problems)
    elseif mode == "NS"
        glossary = ...
            ["u_t"      , "First time-derivative of u"; ...
            "u_tt"      , "Second time-derivative of u"; ...
            "uu_x"      , "Advection of u"; ...
            "u_xx"      , "Laplacian of u"; ...
            "u"         , "Linear in u"; ...
            "u3"        , "Linear in u with velocity square pre-factor"; ...
            "p2u"       , "Linear in u with pressure square pre-factor"; ...
            "dp"        , "Gradient of pressure"; ...
            "pdp"       , "Pressure squared gradient"; ...
            "dvv"       , "Velocity squared gradient"; ...
            "pu"        , "Pressure times velocity"; ...
            "pu_t"      , "p times time derivative of u"; ...
            "up_t"      , "u times time derivative of p"; ...
            %"pu_xx"     , "p times Laplacian of u"; ...
            %"up_xx"     , "u times Laplacian of p"; ...
            ];
    elseif mode == "div"
        glossary = ...
            ["div_u"      , "Divergence of u"; ...
            "p"           , "Linear in p"; ...
            "p_t"         , "Time derivative of p"; ...
            "p_tt"        , "Second time derivative of p"; ...
            "p2"          , "Quadratic in p"; ...
            "u2"          , "Quadratic in velocity"; ...
            "udp"         , "Advection-like with pressure"; ...
            "p_xx"        , "Laplacian of p"; ...
            "pp_t"        , "p times time derivative of p"; ...
            "pdiv_u"      , "p times divergence of u"; ...
            "u2p"         , "p with u^2 pre-factor"; ...
            "uu_t"        , "Time derivative of velocity squared"; ...
            ];
    end
end